name: CI

on: push

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint mypy safety

    - name: Lint
      run: make lint

    - name: Typecheck
      run: make typecheck

    - name: Safety check
      run: safety check
      env:
        SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
